version: '3.8'

services:
  webtools:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: webtools-app
    restart: unless-stopped
    ports:
      - "5005:80"
    networks:
      - webtools-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  webtools-network:
    driver: bridge

# Uncomment nếu cần persistent volumes
# volumes:
#   webtools-data:
#     driver: local