version: '3.8'

services:
  webtools:
    image: tatsuyakari/webtools:latest
    container_name: webtools-app
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=production
      - PORT=5005
    networks:
      - webtools-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  webtools-network:
    driver: bridge

# Uncomment nếu cần persistent volumes
# volumes:
#   webtools-data:
#     driver: local