// Motivational quotes and fun facts for header display
// These will be displayed randomly every minute for 10 seconds

export const motivationalQuotes = [
  // Motivational & Encouraging
  "You're doing amazing! Keep going! 🌟 (ง •̀_•́)ง",
  "Every small step counts towards your goal! 🚀 ٩(◕‿◕)۶",
  "Focus is your superpower! Use it wisely! ⚡ (｡◕‿◕｡)",
  "You're building something incredible right now! 🏗️ ᕦ(ò_óˇ)ᕤ",
  "Progress, not perfection! You've got this! 💪 (ง'̀-'́)ง",
  "Your future self will thank you for this focus! 🙏 (◡ ‿ ◡)",
  "Deep work = Deep results! Stay in the zone! 🎯 ಠ_ಠ",
  "You're training your brain like a muscle! 🧠💪 ᕙ(⇀‸↼‶)ᕗ",
  "Consistency beats intensity every time! 🔄 (•̀ᴗ•́)و",
  "You're in the flow state - ride the wave! 🌊 ヽ(´▽`)/",
  "Success is the sum of small efforts repeated daily! 📈 (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
  "You're not just busy, you're productive! 🎯 (｡•̀ᴗ-)✧",
  "Every minute of focus is a victory! 🏆 \\(^o^)/",
  "You're creating your own luck through hard work! 🍀 (◕‿◕)♡",
  "Discipline is choosing between what you want now and what you want most! 🎯 (¬‿¬)",
  "You're planting seeds for your future harvest! 🌾 (´∀｀)♡",
  "Excellence is a habit, not an act! ⭐ (☆▽☆)",
  "You're becoming the person you've always wanted to be! 🦋 (✿◠‿◠)",
  "Great things never come from comfort zones! 🚀 (╯°□°）╯",
  "You're writing your success story one focused minute at a time! ✍️ (◉‿◉)",
  "The only impossible journey is the one you never begin! 🛤️ ლ(╹◡╹ლ)",
  "You're not just working, you're crafting your masterpiece! 🎨 (ﾉ´ヮ`)ﾉ*: ･ﾟ",
  "Focus is the bridge between dreams and reality! 🌉 (◕‿◕)✨",
  "You're building momentum with every focused session! ⚡ ᕕ( ᐛ )ᕗ",
  "Success is not final, failure is not fatal - it's the courage to continue! 💪 (ง ͠° ͟ل͜ ͡°)ง",
  "You're turning your potential into reality! ✨ (ﾉ◕ヮ◕)ﾉ",
  "Every focused moment is an investment in your dreams! 💰 (◡ ‿ ◡ ✿)",
  "You're not behind, you're exactly where you need to be! 🎯 (´｡• ᵕ •｡`) ♡",
  "Persistence beats resistance every time! 🔥 ᕦ(ò_óˇ)ᕤ",
  "You're creating the life you've always imagined! 🌈 ヽ(°〇°)ﾉ",
  
  // Fun & Stress Relief
  "Time to breathe! Your brain needs oxygen too! 🫁 (´∀｀)σ",
  "Smile! It releases endorphins and boosts focus! 😊 (◕‿◕)",
  "Stretch those shoulders! Your body will love you! 🤸‍♀️ ＼(^o^)／",
  "Remember: Progress over perfection always! ✨ (｡◕‿◕｡)",
  "You're not just working, you're growing! 🌱 ヽ(´▽`)/",
  "Take a moment to appreciate how far you've come! 🎉 \\(^o^)/",
  "Your brain is like a muscle - rest makes it stronger! 💤 (˘▾˘)~♪",
  "Hydrate! Your brain is 75% water! 💧 (っ˘ڡ˘ς)",
  "You're doing better than you think you are! 🌈 (◡ ‿ ◡)",
  "Every expert was once a beginner! Keep learning! 📚 (ﾉ◕ヮ◕)ﾉ",
  "Laughter is the best medicine for stress! 😂 \\(≧∇≦)/",
  "Take a deep breath - you've got this! 🌬️ (´｡• ᵕ •｡`)",
  "Your stress is temporary, your growth is permanent! 🌱 (◕‿◕)♡",
  "Remember to be kind to yourself today! 💝 (´∀｀)♡",
  "You're allowed to take breaks - they make you stronger! ☕ (¬‿¬)",
  "Celebrate small wins - they add up to big victories! 🎊 ヽ(°〇°)ﾉ",
  "Your mental health matters more than your to-do list! 🧠💚 (◡ ‿ ◡ ✿)",
  "It's okay to not be perfect - you're human! 🤗 (´∀｀)σ",
  "Take time to enjoy the journey, not just the destination! 🛤️ (◕‿◕)✨",
  "You're doing your best, and that's enough! 🌟 (｡◕‿◕｡)",
  "Stress is just excitement without breath! 🌬️ (¬‿¬)",
  "You're stronger than your strongest excuse! 💪 ᕦ(ò_óˇ)ᕤ",
  "Take a moment to appreciate this beautiful day! ☀️ ヽ(´▽`)/",
  "Your peace of mind is worth protecting! 🕊️ (◡ ‿ ◡)",
  "Remember: you're a work in progress, not a finished product! 🎨 (´∀｀)♡",
  "It's okay to rest - even machines need maintenance! 🔧 (˘▾˘)~♪",
  "You're not lazy, you're recharging! 🔋 (っ˘ڡ˘ς)",
  "Stress less, smile more! 😊 (◕‿◕)",
  "You're exactly where you're supposed to be right now! 📍 (｡◕‿◕｡)",
  "Take time to smell the roses today! 🌹 \\(^o^)/",
  
  // Random Fun Facts
  "Fun fact: Octopuses have 3 hearts! 🐙❤️",
  "Did you know? Honey never spoils! 🍯",
  "Bananas are berries, but strawberries aren't! 🍌🍓",
  "A group of flamingos is called a 'flamboyance'! 🦩",
  "Dolphins have names for each other! 🐬",
  "The human brain uses 20% of your body's energy! 🧠⚡",
  "There are more trees on Earth than stars in the galaxy! 🌳⭐",
  "A day on Venus is longer than its year! 🪐",
  "Wombat poop is cube-shaped! 🟫",
  "Sharks are older than trees! 🦈🌲",
  "A group of owls is called a 'parliament'! 🦉",
  "Penguins have knees! 🐧",
  "A shrimp's heart is in its head! 🦐❤️",
  "Butterflies taste with their feet! 🦋👅",
  "A group of pandas is called an 'embarrassment'! 🐼",
  "Elephants can't jump! 🐘",
  "A group of crows is called a 'murder'! 🐦‍⬛",
  "Koalas sleep 22 hours a day! 🐨💤",
  "A group of jellyfish is called a 'smack'! 🪼",
  "Sloths only defecate once a week! 🦥",
  "A group of hedgehogs is called a 'prickle'! 🦔",
  "Giraffes only need 5-30 minutes of sleep per day! 🦒",
  "A group of ferrets is called a 'business'! 🦦",
  "Cats have 32 muscles in each ear! 🐱👂",
  "A group of pugs is called a 'grumble'! 🐶",
  "Hummingbirds are the only birds that can fly backwards! 🐦",
  "A group of unicorns is called a 'blessing'! 🦄",
  "Sea otters hold hands while sleeping! 🦦🤝",
  "A group of rabbits is called a 'fluffle'! 🐰",
  "Lobsters were once considered poor people's food! 🦞",
  "Wombat poop is cube-shaped to prevent it from rolling away! 🟫 (◕‿◕)",
  "Frogs can freeze solid without dying! 🐸❄️ (｡◕‿◕｡)",
  "The Turritopsis dohrnii jellyfish is biologically immortal! 🪼∞ (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
  "A cow gives nearly 200,000 glasses of milk in its lifetime! 🐄🥛 (´∀｀)♡",
  "Reindeer eyeballs turn blue in winter! 🦌👁️ (¬‿¬)",
  "Koala fingerprints are so similar to humans they've confused crime scenes! 🐨🔍 (◉‿◉)",
  "A grizzly bear's bite can crush a bowling ball! 🐻🎳 ᕦ(ò_óˇ)ᕤ",
  "Sloths take up to 30 days to digest a single leaf! 🦥🍃 (˘▾˘)~♪",
  "A blue whale's tongue weighs as much as an adult elephant! 🐋👅 (╯°□°）╯",
  "Penguins have an organ that converts saltwater to freshwater! 🐧💧 (◡ ‿ ◡ ✿)",
  "A giraffe's tongue is 20 inches long and dark blue! 🦒👅 ヽ(´▽`)/",
  "Dragonflies have been on Earth for 300 million years! 🪲⏰ (ง •̀_•́)ง",
  "A flea can jump 350 times its body length! 🦟🏃‍♂️ ᕕ( ᐛ )ᕗ",
  "Starfish do not have brains! ⭐🧠❌ (´∀｀)σ",
  "It rains diamonds on Jupiter and Saturn! 💎🌧️ \\(^o^)/",
  "The human brain generates 12-25 watts of electricity! 🧠⚡ (｡•̀ᴗ-)✧",
  "The Eiffel Tower grows 15 cm taller in summer! 🗼📏 (◕‿◕)✨",
  "Sound cannot travel in space - no medium! 🌌🔇 (¬‿¬)",
  "A teaspoon of neutron star weighs 6 billion tons! 🥄⭐ ᕙ(⇀‸↼‶)ᕗ",
  "Sunflowers can clean up radioactive waste! 🌻☢️ (ﾉ◕ヮ◕)ﾉ",
  "Freshly cut grass smell is a plant's distress signal! 🌱😱 (◡ ‿ ◡)",
  "Water can exist in three states simultaneously! 💧🧊💨 (☆▽☆)",
  "The universe has no center and constantly expands! 🌌📈 ヽ(°〇°)ﾉ",
  "Bananas are radioactive due to potassium! 🍌☢️ (´｡• ᵕ •｡`)",
  "Light from the Sun takes 8 minutes 20 seconds to reach Earth! ☀️⏱️ (◕‿◕)",
  "Mars has a volcano three times Mount Everest's size! 🔴🌋 ᕦ(ò_óˇ)ᕤ",
  "The first black hole photo was captured in 2019! 🕳️📸 (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
  "Lightning is five times hotter than the Sun's surface! ⚡🌡️ (ง'̀-'́)ง",
  "Earth is slightly flattened at the poles! 🌍📐 (◉‿◉)",
  "Cleopatra was of Greek descent, not Egyptian! 👑🇬🇷 (¬‿¬)",
  "Roman soldiers were sometimes paid with salt! 🧂💰 (´∀｀)♡",
  "Vikings reached North America before Columbus! ⛵🗺️ ᕕ( ᐛ )ᕗ",
  "Ketchup was sold as medicine in the 1830s! 🍅💊 (◕‿◕)",
  "The shortest war lasted only 38 minutes! ⏰⚔️ \\(≧∇≦)/",
  "The Leaning Tower of Pisa was never straight! 🗼📐 (╯°□°）╯",
  "In Switzerland, owning one guinea pig is illegal! 🇨🇭🐹 (｡◕‿◕｡)",
  "Scotland's national animal is the unicorn! 🏴󠁧󠁢󠁳󠁣󠁴󠁿🦄 \\(^o^)/",
  "The ampersand (&) represents the Latin word 'et'! & (◡ ‿ ◡ ✿)",
  "High heels were originally worn by male soldiers! 👠⚔️ ᕙ(⇀‸↼‶)ᕗ",
  "The first computer mouse was made of wood! 🖱️🪵 (´∀｀)σ",
  "Purple dye was once more expensive than gold! 💜💰 (☆▽☆)",
  "The Great Wall of China isn't visible from the moon! 🏯🌙❌ (¬‿¬)",
  "The world's oldest recipe is for beer! 🍺📜 (っ˘ڡ˘ς)",
  "Your stomach can dissolve razor blades! 🔪💀 (ง •̀_•́)ง",
  "You're taller in the morning than evening! 📏🌅 (◕‿◕)",
  "Your brain is more active when sleeping! 🧠😴 (˘▾˘)~♪",
  "The jaw muscle is the strongest in your body! 💪🦷 ᕦ(ò_óˇ)ᕤ",
  "Humans share 60% DNA with bananas! 🧬🍌 (◉‿◉)",
  "Your nose can remember 50,000 different scents! 👃🌸 (ﾉ◕ヮ◕)ﾉ",
  "Average person walks 5 times around the world! 🚶‍♂️🌍 ᕕ( ᐛ )ᕗ",
  "Goosebumps are an evolutionary leftover trait! 🪿💪 (´∀｀)♡",
  "You can't hum while holding your nose closed! 🎵👃 (¬‿¬)",
  "The small intestine is about 22 feet long! 🫁📏 (◡ ‿ ◡)",
  "Humans are the only animals that blush! 😊🌹 (◕‿◕)♡",
  "Your heart beats 100,000 times daily! ❤️⏰ (｡•̀ᴗ-)✧",
  "Eyes can distinguish 10 million different colors! 👁️🌈 \\(^o^)/",
  "Sneezes travel up to 100 miles per hour! 🤧💨 ᕙ(⇀‸↼‶)ᕗ",
  "Stomach acid is classified as corrosive! 🔥💀 (ง'̀-'́)ง",
  "M&Ms stands for 'Mars' and 'Murrie'! 🍫👥 (´∀｀)σ",
  "Twitter's official bird is named Larry! 🐦📱 (◕‿◕)",
  "A 'jiffy' is 1/100th of a second! ⚡⏱️ (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
  "'Avocado' comes from Aztec word for 'testicle'! 🥑😳 (¬‿¬)",
  "It's impossible to lick your own elbow! 👅💪❌ (◉‿◉)",
  "The dot over 'i' and 'j' is called a tittle! ⚫📝 (｡◕‿◕｡)",
  "The longest word without vowels is 'rhythms'! 🎵📝 ヽ(´▽`)/",
  "In Japan, sumo wrestlers making babies cry brings luck! 🇯🇵👶 (´∀｀)♡",
  "Fear of long words: 'hippopotomonstrosesquippedaliophobia'! 😰📚 (╯°□°）╯",
  "Crocodiles cannot stick their tongues out! 🐊👅❌ (¬‿¬)",
  "The lighter was invented before the match! 🔥💡 (◕‿◕)✨",
  "Google's original name was 'Backrub'! 🔍👋 (◡ ‿ ◡ ✿)",
  "A single spaghetti strand is called 'spaghetto'! 🍝1️⃣ (´∀｀)σ",
  "Shoelace plastic tips are called 'aglets'! 👟🔗 (｡•̀ᴗ-)✧",
  "More chess game iterations than atoms in universe! ♟️🌌 \\(≧∇≦)/",
  "Hawaiian alphabet has only 12 letters! 🏝️🔤 (◕‿◕)",
  "Dr. Seuss coined the word 'nerd'! 🤓📚 ᕕ( ᐛ )ᕗ",
  "Carrots were originally purple! 🥕💜 (☆▽☆)",
  "Hashtag symbol (#) is called 'octothorpe'! #️⃣📝 (¬‿¬)",
  "Barbie's full name is Barbara Millicent Roberts! 💄👱‍♀️ (´∀｀)♡",
  "Pigs physically cannot look up at the sky! 🐷👆❌ (◉‿◉)",
  "'Dreamt' is the only word ending in 'mt'! 💭📝 (˘▾˘)~♪",
  "Antarctica is the world's largest desert! 🐧🏜️ ᕦ(ò_óˇ)ᕤ",
  
  // Productivity Tips
  "Pro tip: The 2-minute rule - if it takes less than 2 minutes, do it now! ⏰ (｡•̀ᴗ-)✧",
  "Remember: Single-tasking beats multitasking! 🎯 ಠ_ಠ",
  "Your environment shapes your focus - optimize it! 🏠 (◕‿◕)",
  "The best time to plant a tree was 20 years ago. The second best time is now! 🌳 ᕦ(ò_óˇ)ᕤ",
  "Small wins create big momentum! Celebrate them! 🎊 \\(^o^)/",
  "Your attention is your most valuable resource! 💎 (¬‿¬)",
  "Quality over quantity - always! ⭐ (｡◕‿◕｡)",
  "The magic happens outside your comfort zone! 🪄 (╯°□°）╯",
  "Comparison is the thief of joy - focus on your journey! 🛤️ (◡ ‿ ◡)",
  "Done is better than perfect! Ship it! 🚢 ᕕ( ᐛ )ᕗ",
  "Batch similar tasks together for maximum efficiency! 📦 (ง •̀_•́)ง",
  "Use the Pomodoro Technique - work in focused sprints! 🍅 (ﾉ◕ヮ◕)ﾉ",
  "Eliminate distractions before they eliminate your focus! 🚫 ಠ_ಠ",
  "Plan your day the night before! 📅 (´∀｀)♡",
  "Energy management beats time management! ⚡ ᕙ(⇀‸↼‶)ᕗ",
  "Start with your most important task! 🎯 (ง'̀-'́)ง",
  "Use the 80/20 rule - focus on what matters most! 📊 (｡•̀ᴗ-)✧",
  "Take breaks before you need them! ☕ (˘▾˘)~♪",
  "Organize your workspace for maximum productivity! 🗂️ (◕‿◕)✨",
  "Set clear boundaries between work and rest! 🚧 (¬‿¬)",
  "Use technology to automate repetitive tasks! 🤖 ヽ(°〇°)ﾉ",
  "Track your time to understand where it goes! ⏱️ (◉‿◉)",
  "Say no to good opportunities to say yes to great ones! ✋ ಠ_ಠ",
  "Review and adjust your systems regularly! 🔄 (◕‿◕)",
  "Focus on systems, not just goals! ⚙️ (｡◕‿◕｡)",
  "Use deadlines to create urgency! ⏰ (ง •̀_•́)ง",
  "Delegate tasks that others can do better! 🤝 (´∀｀)σ",
  "Invest in tools that save you time! 🛠️ ᕦ(ò_óˇ)ᕤ",
  "Learn to work with your natural energy rhythms! 🌊 ヽ(´▽`)/",
  "Document your processes for future efficiency! 📝 (◡ ‿ ◡ ✿)",
];

export const getRandomQuote = (): string => {
  return motivationalQuotes[Math.floor(Math.random() * motivationalQuotes.length)];
};

export const shouldShowQuote = (startTime: number): boolean => {
  const now = Date.now();
  const elapsed = now - startTime;
  const minutesPassed = Math.floor(elapsed / 60000); // 60000ms = 1 minute
  const secondsInCurrentMinute = Math.floor((elapsed % 60000) / 1000);
  
  // Show quote for 20 seconds at the start of each minute
  return minutesPassed > 0 && secondsInCurrentMinute < 20;
};